name: Generate Profile Summary Cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: {}

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: felipe-ssantos
          THEME: github_dark